### ISSUE TITLE
event hub receiver always pulls old messages

### ISSUE THREAD

**Issue by cjpraful** [noodlefrenzy/node-sbus-amqp10#6]
HI i am trying to receive message from event hub.When I ran the example program "simple_eventhub_client.js", i was receiving the old messages. Is it the normal behaviour? is there any alternative to restrict messages to unconsumed message or new messages.

**Comment by robblovell** [comment]
Normally, when you pull from an event hub, you need to set "Check Points" to keep track of the location just past the 'last message processed'.  This is a client side responsibility.  Currently, this code's checkpointing mechanism doesn't work.  

See: https://github.com/noodlefrenzy/node-sbus-amqp10/issues/5

**Comment by noodlefrenzy** [comment]
@cjpraful This is, as @robblovell says, due to the way Event Hubs work. You would need to specify an offset on the client side to ensure it only pulls messages after a given date or checkpoint (see https://github.com/noodlefrenzy/node-amqp10/blob/master/test/integration/servicebus/eventhubs/client.test.js#L53 for an example).

This library is a general purpose AMQP 1.0 library, so adding functionality specifically for Event Hub checkpointing is beyond its remit. I have a special-purpose library (node-sbus-amqp10) for that, but it has not yet been updated to use V2 of this as its core: https://github.com/noodlefrenzy/node-sbus-amqp10/issues/4. I'm planning on working on that shortly (now that I'm back from holiday), but as this is my free-time project it could take some time.

Closing this issue as the underlying problem of setting the x-header is fixed.

**Comment by noodlefrenzy** [comment]
Sigh, I was navigating between projects and didn't realize I'd moved to node-sbus-amqp10. Thought I was still on node-amqp10. Reopening, and my apologies for being a big dork.

**Comment by cjpraful** [comment]
@robblovell @noodlefrenzy apologies for the delay in response. As per your suggestion i had set check points and with that i am setting offset next time when i start so as to get the latest message only from event hub. Thankyou for the help .
